eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: ZUULGATE
zuul:
  routes:
    api-a:
      path: /hi_server/**
      serviceId: RIBBON
    #api-b:
      #path: /api-b/**
      #serviceId: service-feign